### ISSUE TITLE
where are my coins?

### ISSUE THREAD

**Issue by madtomic** [BTCPrivate/BTCP-Rebase#110]
I just got my wallet sync and all my coins are gone? 

From my understanding, you guys were targeting shielded coins. Why are you burning my coins that never moved since I claimed them from snapshot. You can see that all coins were legit from 1:1 exchanged.

My address
https://explorer.btcprivate.org/address/b1BFy2UAo4RNVo5PD8nH4XMihqpZUijaTor

![image](https://user-images.githubusercontent.com/6004542/54731165-0b017080-4b63-11e9-96cf-e7df34bdd832.png)

**Comment by interbiznw** [comment]
You would have had to have "claimed" them after the fork as has been stated since the fork. The Coinburn was in the whitepaper since day 1.

If you claimed them and moved them since the fork day, then they would not have been burned. Also if they were in a transparent address they would have nothing to do with the shielded burn either.

So either you never moved your coins out of the original address(Which would have consisted of you importing your ZCL private key into the BTCP wallet and moving those coins out of the address they appeared in on the btcp blockchain to ANOTHER new Btcp address.

OR your current wallet is not fully synced and showing the balance of that address.

**Comment by madtomic** [comment]
Everything was fine until this bullshit nonsense with burning shielded coins. I guess, my legit coins got burned with it. These coins were claimed and imported into BTCP wallet after BTCP successfully forked, Now why the hell would you burn coins that isn't the issue and as you can see from transaction. These coins were mined LONG before the BTCP was even thought of. These coins were never moved as you can see in the transaction history of this address. Now, who do I talk to to reinstate my wallet funds? I read there is some fund setup with claims. A support contact would be nice since there is no support page from the official site.

**Comment by mattpass** [comment]
@madtomic you losing your coins has nothing to do with burning the shielded coins (since yours are under a transparent address). What's happened is you didn't follow the initial claiming instructions (in short: "access your new BTCP from the fork AND move them in readiness for a future coinburn"). It was also detailed in the whitepaper it could happen 1 year on and there's been plenty of announcements and chatter in just about all BTCP's social media channels.

**Comment by SnippleRifsky** [comment]
The burning of **unmoved** coins has been in the whitepaper from the start so if you didn't know about it, it was due to a lack of proper research.
The shielded burn and the burn of unmoved coins are 2 separate things.
As it was said from the beginning and reiterated several times on several occasions coins had to be moved at least once in order to not be burned, simply importing you BTC/ZCL keys did not "claim" your BTCP.

**Comment by mattpass** [comment]
Also - the claim process is for the approx 20k shielded BTCP that were burnt. People who had these destroyed are fully entitled to have them reimbursed. but that doesn't include your transparent address shown above.

Am going to close this issue as it has nothing to do with rebase repo.

**Comment by madtomic** [comment]
So, where can I go and file a claim for the loss? Even with ZenCash changing to Horizen and forking few times since forked. My coins are still in the same address it was forked from. I have no reason to move then as I don't need to use them. You guys should think and look into adding a way for owners of unshielded address to reclaim their coins due to this.
